name: BikeCrossing
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_fonts: ^4.0.3
  flutter_riverpod: ^2.3.5
  flutter_svg: ^1.1.6
  intl: ^0.18.1
  supabase_flutter: ^1.8.1
  flutter_dotenv: ^5.0.2
  supabase_auth_ui: ^0.1.0+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: "^0.13.0"
  flutter_native_splash: ^2.2.19


flutter_native_splash:
  #color: "#F7F8F7"
  #color: "#ffffff"
  #background_image: assets/images/splash.png
  #image: assets/images/splash_image_icon.png
  background_image: assets/images/splash_image.jpg
  full_screen: true
  #Run Command to auto generate splash screen: "flutter pub run flutter_native_splash:create"
  android_12:
    color: "#F7F8F7"
    image: assets/images/onboarding_bg.jpg
    #background_image: assets/images/onboarding_bg.jpg


flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo_icon.jpg"
  min_sdk_android: 21 # android min sdk min:16,default 21
  #Run Command to auto generate logo: "flutter pub run flutter_launcher_icons"

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
     - assets/images/
     - assets/gifs/
     - assets/icons/
     - .env


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
